const endpoints = {
  ADMIN_LOGIN: "admin/login",
  GET_ADMIN_LEADERBOARD:"admin/leaderboard",
  LOGIN: "users/login",
  REGISTER: "users/signup",
  GET_TOTAL_USERS:"profile/total-competing-users",
  FORGET_PASSWORD_REQUEST_OTP: "users/request-otp",
  RESET_NEW_PASSWORD: "users/set-new-password",
  GET_DASHBOARD_DATA: "dashboard/details",
  GET_CHECK_IN_DATA: "checkin/details",
  OTP_VERIFY: "users/verify-otp",
  OTP_RESEND:"users/resend-otp",
  POST_CHECK_IN_DATA: "checkin/add-remove-checkin",
  BOOK_COACHING_SESSION: "sessions/book-coaching-session",
  POST_REFERAL_DATA: "referals/create",
  POST_SUPPORT_DATA: "support/create",
  POST_DOCTOR_DATA:"support/talk-to-doc",
  GET_PROFILE_DETAIL: "profile/details",
  POST_ONBOARDING_PLANS:"onboarding/set-plans",
  GET_TOP_USERS: "leaderboard/all",
  POST_NOTIFICATION: "profile/notification-settings",
  GET_PROFILE_DETAILS: "profile/details",
  UPDATE_PASSWORD: "profile/change-password",
  UPATE_PROFILE_SETTINGS: "profile/notification-settings",
  UPDATE_PROFILE_DATA: "profile/update-profile",
  CREATE_POST: "community/create-post",
  GET_POSTS: "community/posts",
  GET_POST_COMMENTS: "community/comments",
  CREATE_COMMENT: "community/create-comment",
  DELETE_PROFILE_IMAGE:"profile/delete-profile-image",
  GET_ADMIN_DATA:"admin/dashboard",
  GET_NOTIFICATIONS: "notifications/all",
  EDIT_POST: "community/edit-post",
  DELETE_POST:"community/delete-post",
  STRIPE_PAYMENT: "payments/subscription-intent",
  BOOKING_SESSSION_PAYMENT:"payments/booking-session-intent",
  PREVIOUS_BOOKING_SESSION: '/sessions/get-booking-sessions',
  POST_LIKE: "community/like",
  GET_POST_BY_ID:"community/get-post",
  SET_COUPON_CODE:'/admin/create-coupon',
  USE_COUPON_CODE:'/profile/use-coupon',
  ADMIN_USER_CHECKIN_DATA:"/admin/user-chart-data",
  GET_COUPONS:"/admin/get-coupons",
  DELETE_COUPON:"/admin/delete-coupon/",
  TOGGLE_COUPON:"/admin/toggle-coupon-one-time-use",
};

export default endpoints;


